### ISSUE TITLE
Support PiggyEnchants and Effects

### ISSUE THREAD

**Issue by Hytlenz** [AndreasHGK/EasyKits#1]
As the title said. Btw this plugin is good for making kits ingame

**Comment by IzukuMidoriyaPHP** [comment]
yea piggycustomenchants will be cool to be added

**Comment by AndreasHGK** [comment]
Effects are planned and I could add them in the next beta release.
Ill add customenchants too

**Comment by AndreasHGK** [comment]
The new version has effects

**Comment by AndreasHGK** [comment]
I have now also added PiggyCustomEnchants support.
