### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TetroYT** [AndreasHGK/EasyKits#12]
![40068DBD-8F68-46E1-A0E1-C09C579D432B](https://user-images.githubusercontent.com/49662383/65496374-3b2e2100-deb0-11e9-8742-d36f645629ff.png)

none opped players get this error when selecting a certain category but im like 100% sure ive set the permissions right i cant find any mistakes or spelling mistakes

**Comment by ZZWILLIAMXXTrue** [comment]
I think it has something to do with creating the form not permissions

**Comment by AndreasHGK** [comment]
This is a bug that appears when a kit form is created with 0 kits (ops dont get this because they have permission to see all kits). I will fix this.

**Comment by AndreasHGK** [comment]
This should now work.

**Comment by TetroYT** [comment]
thanks ill try it
