### ISSUE TITLE
Suggestion [PurePerms]

### ISSUE THREAD

**Issue by Play2KillTV** [AndreasHGK/EasyKits#13]
Is it possible if the plugin does not need a pureperms plugin for a player to use it every day? Like /givekitperm {player} {kit}. So that a player can have a kit without the need of changing groups from pureperms.

**Comment by AndreasHGK** [comment]
Alright, I'll add /givekitperm and /removekitperm in a future release

**Comment by Play2KillTV** [comment]
Ok thank you.

**Comment by AndreasHGK** [comment]
I have decided not to implement this, since this is not a permissions plugin. Permissions are built into pocketmine and you just need a plugin to manage them.
