### ISSUE TITLE
/kit doesnt work

### ISSUE THREAD

**Issue by darkadams** [AndreasHGK/EasyKits#15]
When I'm OP and I do /kit it opens up a ui but when it is normal players with no op /kit doesnt it work it just opens up a ui that says error and 
  The title says  Error creating Form and then the text it says
Recieved invalid form jason.Error:
:Could not find required property 'buttons'
Thank you pls fix this my server is almost complete and I need this plugin rlly badly I made so much kits

**Comment by AndreasHGK** [comment]
This usually occurs when the player does not have permission to see any kits. Try using the latest dev build and see if the issue still occurs. If it does, please tell me if you're using categories and if you are show the categories.yml file

**Comment by AndreasHGK** [comment]
I made a new build (available here: https://poggit.pmmp.io/ci/AndreasHGK/EasyKits/EasyKits , just get the first one) which might have fixed your problem.

**Comment by darkadams** [comment]
Thanks so much know it works 100 percent

**Comment by AndreasHGK** [comment]
Thats great to hear! If you encounter any other issues, feel free to report them as well.

**Comment by darkadams** [comment]
When players do /kit it says u dont have permission to view any categories.
Please help and Thanks
