### ISSUE TITLE
I just installed ur recent easykit plugin and i got an issue

### ISSUE THREAD

**Issue by darkadams** [AndreasHGK/EasyKits#16]
When players do /kit it says u dont have permission to view any categories. Please help and Thanks

**Comment by AndreasHGK** [comment]
You need to give your players permission to view categories. (and make sure u actually have categories). Either put a category on unlocked or grant someone the easykits.category.<categoryname> permission.

**Comment by darkadams** [comment]
Still dont work

**Comment by darkadams** [comment]
I did /setgperm Guest easykits.category and that didn't work so I did
/setgperm Guest easykits.category.command and still didn't work  I dont
know what I'm doing wrong can u help me? Players cant use /kit it says you
dont have permission to view any categories and also I do have categories.

**Comment by AndreasHGK** [comment]
You need to give them the easykits.category.name permission

**Comment by darkadams** [comment]
I did /setgperm Guest easykits.category.name and then I did /setgperm Guest
easykits.category.Guest and it still says you dont have permission to view
any categories.

**Comment by darkadams** [comment]
Nvm xD I fixed it

**Comment by AndreasHGK** [comment]
Alright. If you encounter another issue, tell me.

**Comment by darkadams** [comment]
Players cant use lock category's.whats  the perm to allow them to use it
like for ranks. So for example  Member rank should be the only one allowed
to use Member Category and use Member kit?

**Comment by darkadams** [comment]
Um how do u make it so when a rank can use that category only for example
Member rank should be the only allowed to use Member category.

**Comment by AndreasHGK** [comment]
You put the category on locked and give them the permission for the category

**Comment by darkadams** [comment]
I did but it dont work
