### ISSUE TITLE
/givekit issue

### ISSUE THREAD

**Issue by TetroYT** [AndreasHGK/EasyKits#18]
when i use the /givekit command sometimes it works and sometimes it doesnt and i found out that when it doesnt work it opens up the menu for someone random on the server and it works for them even if they dont have permission to select that kit please fix

**Comment by AndreasHGK** [comment]
I fixed the issue. Thanks for bringing this to my attention. ( use the latest build from here: https://poggit.pmmp.io/ci/AndreasHGK/EasyKits/EasyKits )
