### ISSUE TITLE
KitItems

### ISSUE THREAD

**Issue by Play2KillTV** [AndreasHGK/EasyKits#19]
I think the category "kit items" is a gui. does it need another plugin to work? because it instantly closes when I open it. sorry i have a lot of issues here.

**Comment by AndreasHGK** [comment]
The category kit items in editkit is an inventory. You can not open it if you're close to build limit (or above it) or in the void. You should edit the kit items somewhere in the wilderness and see if that works then. You don't need any other plugins for it to work.

**Comment by Play2KillTV** [comment]
I tried, am so far from spawn and somewhere at 50 to 80 in height and i still cannot open it.

**Comment by AndreasHGK** [comment]
thats weird. Any error messages?

**Comment by Play2KillTV** [comment]
None, actually

**Comment by AndreasHGK** [comment]
It works for other people, so thats weird

**Comment by AndreasHGK** [comment]
I'm closing this because i dont bave enough info to recreate this
