### ISSUE TITLE
Iasue

### ISSUE THREAD

**Issue by darkadams** [AndreasHGK/EasyKits#20]
When someone clicks kit member it says they dont have perm.kit Member is only for rank Member.So, I added /setgperm  Member Easykits.kit.Member.But Member rank players still cant use kit Member even tho I added the permission to their rank. How do i fix this?

**Comment by AndreasHGK** [comment]
Try doing the easykits.kit part lowercase and copy the exact kit name behind it (with a . in between)

**Comment by darkadams** [comment]
Um sorry I didnt under stand the part with behind it can u show me an
example? Or do u mean this easykits.kit.Member?

**Comment by AndreasHGK** [comment]
go to kits.yml and copy the name of the kit. If the name is `MeMbEr` then the permission is `easykits.kit.MeMbEr`

**Comment by darkadams** [comment]
Ok I cant test that yet because their is annoy issue where everytime I make
a category and then I make a kit and add it to that category. It keeps
saying Category is empty even though it is not. But if ur op the category
is not empty but when ur a normal play with no op the category is always
empty for some reason ?

**Comment by darkadams** [comment]
Also their is a problem that appeared in my concle after I click on
category and said empty take a look

**Comment by AndreasHGK** [comment]
If it says its empty the player could just have no perms to view the kits inside it
