### ISSUE TITLE
Items Keep Coming Back?

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [AndreasHGK/EasyKits#21]
So my friend DM me on discord saying that he kept getting the kit back over and over again when she left and join. I don’t know what is happening though.

**Comment by AndreasHGK** [comment]
I can't really do much with more info.

**Comment by ZZWILLIAMXXTrue** [comment]
Ok

**Comment by ZZWILLIAMXXTrue** [comment]
My friend said it was fixed
