### ISSUE TITLE
Auto Restart

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [AndreasHGK/EasyKits#24]
Once I downloaded the latest dev and restart my server, it crashes my server making it auto restart without any crash log code thingy.

**Comment by ZZWILLIAMXXTrue** [comment]
Also I didnt edit any config

**Comment by AndreasHGK** [comment]
Its already fixed but for some reason theres no dev build for that. Ill fix that monday asap

**Comment by ZZWILLIAMXXTrue** [comment]
Ok thanks!
