### ISSUE TITLE
Givekit and claim kit bug

### ISSUE THREAD

**Issue by zPqguro** [AndreasHGK/EasyKits#33]
If you run /givekit and select a player, the kit is given to me and not to the chosen player.
Also if you have multiple kits of the same type in your inventory, when you open one the others disappear.

**Comment by JJBirdmanYT** [comment]
I have the same /givekit bug as well.

**Comment by AZLAzz** [comment]
This happens to me too :((

**Comment by AndreasHGK** [comment]
Both of these issues are now fixed
