### ISSUE TITLE
BIG BUG

### ISSUE THREAD

**Issue by AbisGameryt** [AndreasHGK/EasyKits#34]
I have **mentioned this before** but no one replied. EasyKits loses plugin data for some reason. This happens after you restart a couple of times. First it dosen't load in then next restart the data just dissapears. Please fix this data loss issue.

**Comment by Taylarity** [comment]
There's no such issue for me. Make sure you edit files not during the server is running. And, CAPITALIZE isn't doing anything.

**Comment by AndreasHGK** [comment]
is there any messages when loading? For now i suggest backing up the file
