### ISSUE TITLE
Perms not working

### ISSUE THREAD

**Issue by runecrapes** [AndreasHGK/EasyKits#36]
I have been using the plugin smoothly for a few days an now my permissions for the kits arent working and i have no clue why or what i could do to fix it.

  - easykits.kit.Gryffindor
  - easykits.kit.Hufflepuff
  - easykits.kit.Ravenclaw
  - easykits.kit.Slytherin

im not sure if i changed something? or maybe the permmisions changed with the newest .40 dev ?

**Comment by AndreasHGK** [comment]
Have you tried to make it lowercase?

**Comment by runecrapes** [comment]
no but they were working like yeserday with the same perms..

**Comment by runecrapes** [comment]
ill try the lower case

**Comment by runecrapes** [comment]
the category perm works but not the kit its self..

  - easykits.category.Donors
  - easykits.kit.Donors

**Comment by AndreasHGK** [comment]
permissions should work with the latest version
