### ISSUE TITLE
/givekit and chest kit disappearing issue

### ISSUE THREAD

**Issue by AZLAzz** [AndreasHGK/EasyKits#39]
Everything works smoothly, except when i do /givekit (both UI and command) it gives it to me not to the player I want. And when a player have the same kits in their inventory, if they open one the others disappear.

**Comment by RKAbdul** [comment]
I am currently facing the same problem as well

**Comment by AndreasHGK** [comment]
The but with the givekit UI has now been fixed. It is a available as the latest dev build in poggit.
I will see for the chest bug

**Comment by AndreasHGK** [comment]
The chestkit issue is now also fixed!
