### ISSUE TITLE
Kit Permission Not Working

### ISSUE THREAD

**Issue by laigelplayz** [AndreasHGK/EasyKits#41]
I dont know if i just do it wrong but the permission for kits is not working... So i have a question if the kit Has a Color like § do i need to add a perm easykits.kit.§bElite?? or Just Rmeove §? Anyways if thats not the case i think the plugin having problems!....Also a suggestion Please Update the plugin for more impovements! Thanks;)

**Comment by AndreasHGK** [comment]
try it without the color codes. There is a seperate permission value in the latest versions, be sure to change it and add the correct value in your groups plugin
