### ISSUE TITLE
/Givekit NotWorking

### ISSUE THREAD

**Issue by laigelplayz** [AndreasHGK/EasyKits#42]
When i do /givekit it will open ui and i will choose a player to give the kit and choose what kit to give and when i submit it give the kit to me Not to the player i choosed. Please fixed not a very bad bug but it still a good feature for voting rewards! also suggestion: Can you make it doable without opening ui Like /givekit <player> <KitName> <CustomMessage> so it can be attached in rewards plugin!

**Comment by AndreasHGK** [comment]
You can already use /givekit without the ui, like this: /givekit <player> <kit>

**Comment by AndreasHGK** [comment]
The but with the UI has now been fixed. It is a available as the latest dev build in poggit.
