### ISSUE TITLE
Poggit

### ISSUE THREAD

**Issue by CosmicGhost** [AndreasHGK/EasyKits#5]
Can u put it in .phat in poggit ples

**Comment by AndreasHGK** [comment]
It is already on the poggit dev section.

**Comment by CosmicGhost** [comment]
Rlly can u reply wid a link?

**Comment by AndreasHGK** [comment]
https://poggit.pmmp.io/ci/AndreasHGK/EasyKits/EasyKits

**Comment by AndreasHGK** [comment]
Download the latest one

**Comment by CosmicGhost** [comment]
K thanks
