### ISSUE TITLE
Need help...

### ISSUE THREAD

**Issue by Endiscool11** [AndreasHGK/EasyKits#58]
How can i make it work on slappers/npc's, Like when i punch the slapper/npc then it opens the UI or it shows the kit list. I really need help thanks!

**Comment by Endiscool11** [comment]
what command do i add or what do i need to change on the configs.yml thanks, And one more thing why is my money not decreasing when i buy a kit?

**Comment by ErosionYT** [comment]
> How can i make it work on slappers/npc's, Like when i punch the slapper/npc then it opens the UI or it shows the kit list. I really need help thanks!

Add the kit command to the slapper.

https://github.com/jojoe77777/Slapper

**Comment by Endiscool11** [comment]
Thanks, I know now
