### ISSUE TITLE
Failed to Load Kits

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [AndreasHGK/EasyKits#6]
So I recently added a kit called Overload and when I came on the next day to turn on the server it said it “Failed to load kit Overload.” Im using 3.9.3 Poggit and this is the config all I did was add the kit and changed nothing in config
Overload:
  items:
    0:
      id: 322
      damage: 0
      count: 12
    1:
      id: 466
      damage: 0
      count: 3
    2:
      id: 373
      damage: 22
      count: 1
    3:
      id: 373
      damage: 22
      count: 1
    4:
      id: 373
      damage: 22
      count: 1
    5:
      id: 310
      damage: 0
      count: 1
      lore:
      - ""
      - §8Overload III
      enchants:
        419: 3
        17: 10
    6:
      id: 311
      damage: 0
      count: 1
      lore:
      - ""
      - §8Overload III
      enchants:
        419: 3
        17: 10
    7:
      id: 312
      damage: 0
      count: 1
      lore:
      - ""
      - §8Overload III
      enchants:
        419: 3
        17: 10
    8:
      id: 313
      damage: 0
      count: 1
      lore:
      - ""
      - §8Overload III
      enchants:
        419: 3
        17: 10
    20:
      id: 373
      damage: 22
      count: 1
    21:
      id: 373
      damage: 22
      count: 1
    22:
      id: 373
      damage: 22
      count: 1
    29:
      id: 373
      damage: 22
      count: 1
    30:
      id: 373
      damage: 22
      count: 1
    31:
      id: 373
      damage: 22
      count: 1
  armor: []
  price: 10000000.000000
  cooldown: 0
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: true

**Comment by ZZWILLIAMXXTrue** [comment]
Update: I thought the lore was the problem but when I remove - “” and change - Overload ||| to - “Overload |||” and reload the server it changes it to - Overload ||| removing the “

**Comment by AndreasHGK** [comment]
Could you send the actual config file, because it is veryhard to read without spacing.

**Comment by AndreasHGK** [comment]
You can use the latest dev build to see the error. If you installed the latest dev build ( here https://poggit.pmmp.io/ci/AndreasHGK/EasyKits/EasyKits ), go to pocketmine.yml and make the debug level 2. Then restart the server and copy and paste the error. When done you can put debug back to 1.

**Comment by ZZWILLIAMXXTrue** [comment]
Ok thanks!

**Comment by AndreasHGK** [comment]
Lol this was not a fix to the issue. This was to get the errir
