### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TetroYT** [AndreasHGK/EasyKits#8]
give a kit

the command could be /givekit (kitname) (amount) this would be useful for servers that want to reward their players with a 1 time kit instead of having it unlocked for a life time.

some examples completing quests on skyblock or factions lets say you kill 100 player and you receive 1 good kit.

i hope you lime this idea it would benefit my server and many more

**Comment by TetroYT** [comment]
*update*
/give kit (kitname) (player) (amount)

**Comment by AndreasHGK** [comment]
This is already implemented, except for the (amount) argument. If you execute /givekit ingame it will give a UI but you can also run it using /givekit player kit and just instantly give it. That last thing also works from the console.

**Comment by TetroYT** [comment]
thank you, you can close this if you want great plugin :D
