### ISSUE TITLE
Issue with recent dev build

### ISSUE THREAD

**Issue by TetroYT** [AndreasHGK/EasyKits#9]
i just installed your latest dev build for easy kits and this is the error i got in console
![44B7215B-6B63-419C-9461-732786C2CDCA](https://user-images.githubusercontent.com/49662383/65021706-8df36000-d927-11e9-9cc6-a176106e9013.jpeg)

**Comment by AndreasHGK** [comment]
Your config files are outdated. Enable auto update in config.yml or let all the files regenerate.

**Comment by TetroYT** [comment]
oh ok thanks
